profile = "gpt5"
approval_presets = "auto"

[sandbox_workspace_write]
network_access = true

[profiles.gpt5]
model = "gpt-5.1-codex-max"
model_reasoning_effort = "medium"
approval_policy = "on-request"
sandbox_mode = "workspace-write"

[shell_environment_policy]
inherit = "core"

[tui]
notifications = true

[features]
apply_patch_freeform = true
web_search_request = true
streamable_shell = true
