profile = "gpt5"
sandbox_mode = "workspace-write"
approval_policy = "untrusted"
streamable_shell = true

[sandbox_workspace_write]
network_access = false

[profiles.gpt5]
model = "gpt-5-codex"
model_reasoning_effort = "medium"

[shell_environment_policy]
inherit = "core"

[tui]
notifications = true

[features]
web_search_request = true
